package com.cjw.yolonote.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbFriendRequest implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_request.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_request.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_request.friendId
     *
     * @mbggenerated
     */
    private Integer friendid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_request.friendRemark
     *
     * @mbggenerated
     */
    private String friendremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_request.passFlag
     *
     * @mbggenerated
     */
    private Integer passflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_request.requestTime
     *
     * @mbggenerated
     */
    private Date requesttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_request.auditTime
     *
     * @mbggenerated
     */
    private Date audittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_request.addRemark
     *
     * @mbggenerated
     */
    private String addremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_friend_request
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_request.id
     *
     * @return the value of tb_friend_request.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_request.id
     *
     * @param id the value for tb_friend_request.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_request.userId
     *
     * @return the value of tb_friend_request.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_request.userId
     *
     * @param userid the value for tb_friend_request.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_request.friendId
     *
     * @return the value of tb_friend_request.friendId
     *
     * @mbggenerated
     */
    public Integer getFriendid() {
        return friendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_request.friendId
     *
     * @param friendid the value for tb_friend_request.friendId
     *
     * @mbggenerated
     */
    public void setFriendid(Integer friendid) {
        this.friendid = friendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_request.friendRemark
     *
     * @return the value of tb_friend_request.friendRemark
     *
     * @mbggenerated
     */
    public String getFriendremark() {
        return friendremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_request.friendRemark
     *
     * @param friendremark the value for tb_friend_request.friendRemark
     *
     * @mbggenerated
     */
    public void setFriendremark(String friendremark) {
        this.friendremark = friendremark == null ? null : friendremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_request.passFlag
     *
     * @return the value of tb_friend_request.passFlag
     *
     * @mbggenerated
     */
    public Integer getPassflag() {
        return passflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_request.passFlag
     *
     * @param passflag the value for tb_friend_request.passFlag
     *
     * @mbggenerated
     */
    public void setPassflag(Integer passflag) {
        this.passflag = passflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_request.requestTime
     *
     * @return the value of tb_friend_request.requestTime
     *
     * @mbggenerated
     */
    public Date getRequesttime() {
        return requesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_request.requestTime
     *
     * @param requesttime the value for tb_friend_request.requestTime
     *
     * @mbggenerated
     */
    public void setRequesttime(Date requesttime) {
        this.requesttime = requesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_request.auditTime
     *
     * @return the value of tb_friend_request.auditTime
     *
     * @mbggenerated
     */
    public Date getAudittime() {
        return audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_request.auditTime
     *
     * @param audittime the value for tb_friend_request.auditTime
     *
     * @mbggenerated
     */
    public void setAudittime(Date audittime) {
        this.audittime = audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_request.addRemark
     *
     * @return the value of tb_friend_request.addRemark
     *
     * @mbggenerated
     */
    public String getAddremark() {
        return addremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_request.addRemark
     *
     * @param addremark the value for tb_friend_request.addRemark
     *
     * @mbggenerated
     */
    public void setAddremark(String addremark) {
        this.addremark = addremark == null ? null : addremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_request
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userid=").append(userid);
        sb.append(", friendid=").append(friendid);
        sb.append(", friendremark=").append(friendremark);
        sb.append(", passflag=").append(passflag);
        sb.append(", requesttime=").append(requesttime);
        sb.append(", audittime=").append(audittime);
        sb.append(", addremark=").append(addremark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}