package com.cjw.yolonote.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbNoteBookAuditHistory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book_audit_history.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book_audit_history.managerId
     *
     * @mbggenerated
     */
    private Integer managerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book_audit_history.noteBookId
     *
     * @mbggenerated
     */
    private Integer notebookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book_audit_history.auditTime
     *
     * @mbggenerated
     */
    private Date audittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_note_book_audit_history
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book_audit_history.id
     *
     * @return the value of tb_note_book_audit_history.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book_audit_history.id
     *
     * @param id the value for tb_note_book_audit_history.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book_audit_history.managerId
     *
     * @return the value of tb_note_book_audit_history.managerId
     *
     * @mbggenerated
     */
    public Integer getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book_audit_history.managerId
     *
     * @param managerid the value for tb_note_book_audit_history.managerId
     *
     * @mbggenerated
     */
    public void setManagerid(Integer managerid) {
        this.managerid = managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book_audit_history.noteBookId
     *
     * @return the value of tb_note_book_audit_history.noteBookId
     *
     * @mbggenerated
     */
    public Integer getNotebookid() {
        return notebookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book_audit_history.noteBookId
     *
     * @param notebookid the value for tb_note_book_audit_history.noteBookId
     *
     * @mbggenerated
     */
    public void setNotebookid(Integer notebookid) {
        this.notebookid = notebookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book_audit_history.auditTime
     *
     * @return the value of tb_note_book_audit_history.auditTime
     *
     * @mbggenerated
     */
    public Date getAudittime() {
        return audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book_audit_history.auditTime
     *
     * @param audittime the value for tb_note_book_audit_history.auditTime
     *
     * @mbggenerated
     */
    public void setAudittime(Date audittime) {
        this.audittime = audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_audit_history
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", managerid=").append(managerid);
        sb.append(", notebookid=").append(notebookid);
        sb.append(", audittime=").append(audittime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}