package com.cjw.yolonote.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbNoteLabelData implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_label_data.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_label_data.labelName
     *
     * @mbggenerated
     */
    private String labelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_label_data.managerId
     *
     * @mbggenerated
     */
    private Integer managerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_label_data.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_note_label_data
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_label_data.id
     *
     * @return the value of tb_note_label_data.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_label_data.id
     *
     * @param id the value for tb_note_label_data.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_label_data.labelName
     *
     * @return the value of tb_note_label_data.labelName
     *
     * @mbggenerated
     */
    public String getLabelname() {
        return labelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_label_data.labelName
     *
     * @param labelname the value for tb_note_label_data.labelName
     *
     * @mbggenerated
     */
    public void setLabelname(String labelname) {
        this.labelname = labelname == null ? null : labelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_label_data.managerId
     *
     * @return the value of tb_note_label_data.managerId
     *
     * @mbggenerated
     */
    public Integer getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_label_data.managerId
     *
     * @param managerid the value for tb_note_label_data.managerId
     *
     * @mbggenerated
     */
    public void setManagerid(Integer managerid) {
        this.managerid = managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_label_data.updateTime
     *
     * @return the value of tb_note_label_data.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_label_data.updateTime
     *
     * @param updatetime the value for tb_note_label_data.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_label_data
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", labelname=").append(labelname);
        sb.append(", managerid=").append(managerid);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}