package com.cjw.yolonote.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbNoteBook implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book.noteBookCover
     *
     * @mbggenerated
     */
    private String notebookcover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book.noteBookTitle
     *
     * @mbggenerated
     */
    private String notebooktitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book.noteBookFlag
     *
     * @mbggenerated
     */
    private Integer notebookflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book.noteStar
     *
     * @mbggenerated
     */
    private Integer notestar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book.availableFlag
     *
     * @mbggenerated
     */
    private Integer availableflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_note_book
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book.id
     *
     * @return the value of tb_note_book.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book.id
     *
     * @param id the value for tb_note_book.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book.userId
     *
     * @return the value of tb_note_book.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book.userId
     *
     * @param userid the value for tb_note_book.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book.noteBookCover
     *
     * @return the value of tb_note_book.noteBookCover
     *
     * @mbggenerated
     */
    public String getNotebookcover() {
        return notebookcover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book.noteBookCover
     *
     * @param notebookcover the value for tb_note_book.noteBookCover
     *
     * @mbggenerated
     */
    public void setNotebookcover(String notebookcover) {
        this.notebookcover = notebookcover == null ? null : notebookcover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book.noteBookTitle
     *
     * @return the value of tb_note_book.noteBookTitle
     *
     * @mbggenerated
     */
    public String getNotebooktitle() {
        return notebooktitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book.noteBookTitle
     *
     * @param notebooktitle the value for tb_note_book.noteBookTitle
     *
     * @mbggenerated
     */
    public void setNotebooktitle(String notebooktitle) {
        this.notebooktitle = notebooktitle == null ? null : notebooktitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book.noteBookFlag
     *
     * @return the value of tb_note_book.noteBookFlag
     *
     * @mbggenerated
     */
    public Integer getNotebookflag() {
        return notebookflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book.noteBookFlag
     *
     * @param notebookflag the value for tb_note_book.noteBookFlag
     *
     * @mbggenerated
     */
    public void setNotebookflag(Integer notebookflag) {
        this.notebookflag = notebookflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book.noteStar
     *
     * @return the value of tb_note_book.noteStar
     *
     * @mbggenerated
     */
    public Integer getNotestar() {
        return notestar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book.noteStar
     *
     * @param notestar the value for tb_note_book.noteStar
     *
     * @mbggenerated
     */
    public void setNotestar(Integer notestar) {
        this.notestar = notestar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book.availableFlag
     *
     * @return the value of tb_note_book.availableFlag
     *
     * @mbggenerated
     */
    public Integer getAvailableflag() {
        return availableflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book.availableFlag
     *
     * @param availableflag the value for tb_note_book.availableFlag
     *
     * @mbggenerated
     */
    public void setAvailableflag(Integer availableflag) {
        this.availableflag = availableflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book.createTime
     *
     * @return the value of tb_note_book.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book.createTime
     *
     * @param createtime the value for tb_note_book.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userid=").append(userid);
        sb.append(", notebookcover=").append(notebookcover);
        sb.append(", notebooktitle=").append(notebooktitle);
        sb.append(", notebookflag=").append(notebookflag);
        sb.append(", notestar=").append(notestar);
        sb.append(", availableflag=").append(availableflag);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}