package com.cjw.yolonote.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbNoteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_note
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_note
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_note
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note
     *
     * @mbggenerated
     */
    public TbNoteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_note
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNoteidIsNull() {
            addCriterion("noteId is null");
            return (Criteria) this;
        }

        public Criteria andNoteidIsNotNull() {
            addCriterion("noteId is not null");
            return (Criteria) this;
        }

        public Criteria andNoteidEqualTo(Integer value) {
            addCriterion("noteId =", value, "noteid");
            return (Criteria) this;
        }

        public Criteria andNoteidNotEqualTo(Integer value) {
            addCriterion("noteId <>", value, "noteid");
            return (Criteria) this;
        }

        public Criteria andNoteidGreaterThan(Integer value) {
            addCriterion("noteId >", value, "noteid");
            return (Criteria) this;
        }

        public Criteria andNoteidGreaterThanOrEqualTo(Integer value) {
            addCriterion("noteId >=", value, "noteid");
            return (Criteria) this;
        }

        public Criteria andNoteidLessThan(Integer value) {
            addCriterion("noteId <", value, "noteid");
            return (Criteria) this;
        }

        public Criteria andNoteidLessThanOrEqualTo(Integer value) {
            addCriterion("noteId <=", value, "noteid");
            return (Criteria) this;
        }

        public Criteria andNoteidIn(List<Integer> values) {
            addCriterion("noteId in", values, "noteid");
            return (Criteria) this;
        }

        public Criteria andNoteidNotIn(List<Integer> values) {
            addCriterion("noteId not in", values, "noteid");
            return (Criteria) this;
        }

        public Criteria andNoteidBetween(Integer value1, Integer value2) {
            addCriterion("noteId between", value1, value2, "noteid");
            return (Criteria) this;
        }

        public Criteria andNoteidNotBetween(Integer value1, Integer value2) {
            addCriterion("noteId not between", value1, value2, "noteid");
            return (Criteria) this;
        }

        public Criteria andNotebookidIsNull() {
            addCriterion("noteBookId is null");
            return (Criteria) this;
        }

        public Criteria andNotebookidIsNotNull() {
            addCriterion("noteBookId is not null");
            return (Criteria) this;
        }

        public Criteria andNotebookidEqualTo(Integer value) {
            addCriterion("noteBookId =", value, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotebookidNotEqualTo(Integer value) {
            addCriterion("noteBookId <>", value, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotebookidGreaterThan(Integer value) {
            addCriterion("noteBookId >", value, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotebookidGreaterThanOrEqualTo(Integer value) {
            addCriterion("noteBookId >=", value, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotebookidLessThan(Integer value) {
            addCriterion("noteBookId <", value, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotebookidLessThanOrEqualTo(Integer value) {
            addCriterion("noteBookId <=", value, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotebookidIn(List<Integer> values) {
            addCriterion("noteBookId in", values, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotebookidNotIn(List<Integer> values) {
            addCriterion("noteBookId not in", values, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotebookidBetween(Integer value1, Integer value2) {
            addCriterion("noteBookId between", value1, value2, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotebookidNotBetween(Integer value1, Integer value2) {
            addCriterion("noteBookId not between", value1, value2, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotetitleIsNull() {
            addCriterion("noteTitle is null");
            return (Criteria) this;
        }

        public Criteria andNotetitleIsNotNull() {
            addCriterion("noteTitle is not null");
            return (Criteria) this;
        }

        public Criteria andNotetitleEqualTo(String value) {
            addCriterion("noteTitle =", value, "notetitle");
            return (Criteria) this;
        }

        public Criteria andNotetitleNotEqualTo(String value) {
            addCriterion("noteTitle <>", value, "notetitle");
            return (Criteria) this;
        }

        public Criteria andNotetitleGreaterThan(String value) {
            addCriterion("noteTitle >", value, "notetitle");
            return (Criteria) this;
        }

        public Criteria andNotetitleGreaterThanOrEqualTo(String value) {
            addCriterion("noteTitle >=", value, "notetitle");
            return (Criteria) this;
        }

        public Criteria andNotetitleLessThan(String value) {
            addCriterion("noteTitle <", value, "notetitle");
            return (Criteria) this;
        }

        public Criteria andNotetitleLessThanOrEqualTo(String value) {
            addCriterion("noteTitle <=", value, "notetitle");
            return (Criteria) this;
        }

        public Criteria andNotetitleLike(String value) {
            addCriterion("noteTitle like", value, "notetitle");
            return (Criteria) this;
        }

        public Criteria andNotetitleNotLike(String value) {
            addCriterion("noteTitle not like", value, "notetitle");
            return (Criteria) this;
        }

        public Criteria andNotetitleIn(List<String> values) {
            addCriterion("noteTitle in", values, "notetitle");
            return (Criteria) this;
        }

        public Criteria andNotetitleNotIn(List<String> values) {
            addCriterion("noteTitle not in", values, "notetitle");
            return (Criteria) this;
        }

        public Criteria andNotetitleBetween(String value1, String value2) {
            addCriterion("noteTitle between", value1, value2, "notetitle");
            return (Criteria) this;
        }

        public Criteria andNotetitleNotBetween(String value1, String value2) {
            addCriterion("noteTitle not between", value1, value2, "notetitle");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_note
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_note
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}