package com.cjw.yolonote.pojo;

import java.io.Serializable;

public class TbNoteBookAudit implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book_audit.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book_audit.noteBookId
     *
     * @mbggenerated
     */
    private Integer notebookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book_audit.managerId
     *
     * @mbggenerated
     */
    private Integer managerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book_audit.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book_audit.auditInfo
     *
     * @mbggenerated
     */
    private String auditinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_note_book_audit
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book_audit.id
     *
     * @return the value of tb_note_book_audit.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book_audit.id
     *
     * @param id the value for tb_note_book_audit.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book_audit.noteBookId
     *
     * @return the value of tb_note_book_audit.noteBookId
     *
     * @mbggenerated
     */
    public Integer getNotebookid() {
        return notebookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book_audit.noteBookId
     *
     * @param notebookid the value for tb_note_book_audit.noteBookId
     *
     * @mbggenerated
     */
    public void setNotebookid(Integer notebookid) {
        this.notebookid = notebookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book_audit.managerId
     *
     * @return the value of tb_note_book_audit.managerId
     *
     * @mbggenerated
     */
    public Integer getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book_audit.managerId
     *
     * @param managerid the value for tb_note_book_audit.managerId
     *
     * @mbggenerated
     */
    public void setManagerid(Integer managerid) {
        this.managerid = managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book_audit.status
     *
     * @return the value of tb_note_book_audit.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book_audit.status
     *
     * @param status the value for tb_note_book_audit.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book_audit.auditInfo
     *
     * @return the value of tb_note_book_audit.auditInfo
     *
     * @mbggenerated
     */
    public String getAuditinfo() {
        return auditinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book_audit.auditInfo
     *
     * @param auditinfo the value for tb_note_book_audit.auditInfo
     *
     * @mbggenerated
     */
    public void setAuditinfo(String auditinfo) {
        this.auditinfo = auditinfo == null ? null : auditinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_audit
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", notebookid=").append(notebookid);
        sb.append(", managerid=").append(managerid);
        sb.append(", status=").append(status);
        sb.append(", auditinfo=").append(auditinfo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}