package com.cjw.yolonote.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbNoteBookPullExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated
     */
    public TbNoteBookPullExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNotebookidIsNull() {
            addCriterion("noteBookId is null");
            return (Criteria) this;
        }

        public Criteria andNotebookidIsNotNull() {
            addCriterion("noteBookId is not null");
            return (Criteria) this;
        }

        public Criteria andNotebookidEqualTo(Integer value) {
            addCriterion("noteBookId =", value, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotebookidNotEqualTo(Integer value) {
            addCriterion("noteBookId <>", value, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotebookidGreaterThan(Integer value) {
            addCriterion("noteBookId >", value, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotebookidGreaterThanOrEqualTo(Integer value) {
            addCriterion("noteBookId >=", value, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotebookidLessThan(Integer value) {
            addCriterion("noteBookId <", value, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotebookidLessThanOrEqualTo(Integer value) {
            addCriterion("noteBookId <=", value, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotebookidIn(List<Integer> values) {
            addCriterion("noteBookId in", values, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotebookidNotIn(List<Integer> values) {
            addCriterion("noteBookId not in", values, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotebookidBetween(Integer value1, Integer value2) {
            addCriterion("noteBookId between", value1, value2, "notebookid");
            return (Criteria) this;
        }

        public Criteria andNotebookidNotBetween(Integer value1, Integer value2) {
            addCriterion("noteBookId not between", value1, value2, "notebookid");
            return (Criteria) this;
        }

        public Criteria andFormerbookidIsNull() {
            addCriterion("formerBookId is null");
            return (Criteria) this;
        }

        public Criteria andFormerbookidIsNotNull() {
            addCriterion("formerBookId is not null");
            return (Criteria) this;
        }

        public Criteria andFormerbookidEqualTo(Integer value) {
            addCriterion("formerBookId =", value, "formerbookid");
            return (Criteria) this;
        }

        public Criteria andFormerbookidNotEqualTo(Integer value) {
            addCriterion("formerBookId <>", value, "formerbookid");
            return (Criteria) this;
        }

        public Criteria andFormerbookidGreaterThan(Integer value) {
            addCriterion("formerBookId >", value, "formerbookid");
            return (Criteria) this;
        }

        public Criteria andFormerbookidGreaterThanOrEqualTo(Integer value) {
            addCriterion("formerBookId >=", value, "formerbookid");
            return (Criteria) this;
        }

        public Criteria andFormerbookidLessThan(Integer value) {
            addCriterion("formerBookId <", value, "formerbookid");
            return (Criteria) this;
        }

        public Criteria andFormerbookidLessThanOrEqualTo(Integer value) {
            addCriterion("formerBookId <=", value, "formerbookid");
            return (Criteria) this;
        }

        public Criteria andFormerbookidIn(List<Integer> values) {
            addCriterion("formerBookId in", values, "formerbookid");
            return (Criteria) this;
        }

        public Criteria andFormerbookidNotIn(List<Integer> values) {
            addCriterion("formerBookId not in", values, "formerbookid");
            return (Criteria) this;
        }

        public Criteria andFormerbookidBetween(Integer value1, Integer value2) {
            addCriterion("formerBookId between", value1, value2, "formerbookid");
            return (Criteria) this;
        }

        public Criteria andFormerbookidNotBetween(Integer value1, Integer value2) {
            addCriterion("formerBookId not between", value1, value2, "formerbookid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andFormeruseridIsNull() {
            addCriterion("formerUserId is null");
            return (Criteria) this;
        }

        public Criteria andFormeruseridIsNotNull() {
            addCriterion("formerUserId is not null");
            return (Criteria) this;
        }

        public Criteria andFormeruseridEqualTo(Integer value) {
            addCriterion("formerUserId =", value, "formeruserid");
            return (Criteria) this;
        }

        public Criteria andFormeruseridNotEqualTo(Integer value) {
            addCriterion("formerUserId <>", value, "formeruserid");
            return (Criteria) this;
        }

        public Criteria andFormeruseridGreaterThan(Integer value) {
            addCriterion("formerUserId >", value, "formeruserid");
            return (Criteria) this;
        }

        public Criteria andFormeruseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("formerUserId >=", value, "formeruserid");
            return (Criteria) this;
        }

        public Criteria andFormeruseridLessThan(Integer value) {
            addCriterion("formerUserId <", value, "formeruserid");
            return (Criteria) this;
        }

        public Criteria andFormeruseridLessThanOrEqualTo(Integer value) {
            addCriterion("formerUserId <=", value, "formeruserid");
            return (Criteria) this;
        }

        public Criteria andFormeruseridIn(List<Integer> values) {
            addCriterion("formerUserId in", values, "formeruserid");
            return (Criteria) this;
        }

        public Criteria andFormeruseridNotIn(List<Integer> values) {
            addCriterion("formerUserId not in", values, "formeruserid");
            return (Criteria) this;
        }

        public Criteria andFormeruseridBetween(Integer value1, Integer value2) {
            addCriterion("formerUserId between", value1, value2, "formeruserid");
            return (Criteria) this;
        }

        public Criteria andFormeruseridNotBetween(Integer value1, Integer value2) {
            addCriterion("formerUserId not between", value1, value2, "formeruserid");
            return (Criteria) this;
        }

        public Criteria andPulltimeIsNull() {
            addCriterion("pullTime is null");
            return (Criteria) this;
        }

        public Criteria andPulltimeIsNotNull() {
            addCriterion("pullTime is not null");
            return (Criteria) this;
        }

        public Criteria andPulltimeEqualTo(Date value) {
            addCriterion("pullTime =", value, "pulltime");
            return (Criteria) this;
        }

        public Criteria andPulltimeNotEqualTo(Date value) {
            addCriterion("pullTime <>", value, "pulltime");
            return (Criteria) this;
        }

        public Criteria andPulltimeGreaterThan(Date value) {
            addCriterion("pullTime >", value, "pulltime");
            return (Criteria) this;
        }

        public Criteria andPulltimeGreaterThanOrEqualTo(Date value) {
            addCriterion("pullTime >=", value, "pulltime");
            return (Criteria) this;
        }

        public Criteria andPulltimeLessThan(Date value) {
            addCriterion("pullTime <", value, "pulltime");
            return (Criteria) this;
        }

        public Criteria andPulltimeLessThanOrEqualTo(Date value) {
            addCriterion("pullTime <=", value, "pulltime");
            return (Criteria) this;
        }

        public Criteria andPulltimeIn(List<Date> values) {
            addCriterion("pullTime in", values, "pulltime");
            return (Criteria) this;
        }

        public Criteria andPulltimeNotIn(List<Date> values) {
            addCriterion("pullTime not in", values, "pulltime");
            return (Criteria) this;
        }

        public Criteria andPulltimeBetween(Date value1, Date value2) {
            addCriterion("pullTime between", value1, value2, "pulltime");
            return (Criteria) this;
        }

        public Criteria andPulltimeNotBetween(Date value1, Date value2) {
            addCriterion("pullTime not between", value1, value2, "pulltime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}