package com.cjw.yolonote.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbNoteBookPull implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book_pull.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book_pull.noteBookId
     *
     * @mbggenerated
     */
    private Integer notebookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book_pull.formerBookId
     *
     * @mbggenerated
     */
    private Integer formerbookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book_pull.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book_pull.formerUserId
     *
     * @mbggenerated
     */
    private Integer formeruserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_note_book_pull.pullTime
     *
     * @mbggenerated
     */
    private Date pulltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book_pull.id
     *
     * @return the value of tb_note_book_pull.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book_pull.id
     *
     * @param id the value for tb_note_book_pull.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book_pull.noteBookId
     *
     * @return the value of tb_note_book_pull.noteBookId
     *
     * @mbggenerated
     */
    public Integer getNotebookid() {
        return notebookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book_pull.noteBookId
     *
     * @param notebookid the value for tb_note_book_pull.noteBookId
     *
     * @mbggenerated
     */
    public void setNotebookid(Integer notebookid) {
        this.notebookid = notebookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book_pull.formerBookId
     *
     * @return the value of tb_note_book_pull.formerBookId
     *
     * @mbggenerated
     */
    public Integer getFormerbookid() {
        return formerbookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book_pull.formerBookId
     *
     * @param formerbookid the value for tb_note_book_pull.formerBookId
     *
     * @mbggenerated
     */
    public void setFormerbookid(Integer formerbookid) {
        this.formerbookid = formerbookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book_pull.userId
     *
     * @return the value of tb_note_book_pull.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book_pull.userId
     *
     * @param userid the value for tb_note_book_pull.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book_pull.formerUserId
     *
     * @return the value of tb_note_book_pull.formerUserId
     *
     * @mbggenerated
     */
    public Integer getFormeruserid() {
        return formeruserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book_pull.formerUserId
     *
     * @param formeruserid the value for tb_note_book_pull.formerUserId
     *
     * @mbggenerated
     */
    public void setFormeruserid(Integer formeruserid) {
        this.formeruserid = formeruserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_note_book_pull.pullTime
     *
     * @return the value of tb_note_book_pull.pullTime
     *
     * @mbggenerated
     */
    public Date getPulltime() {
        return pulltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_note_book_pull.pullTime
     *
     * @param pulltime the value for tb_note_book_pull.pullTime
     *
     * @mbggenerated
     */
    public void setPulltime(Date pulltime) {
        this.pulltime = pulltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_pull
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", notebookid=").append(notebookid);
        sb.append(", formerbookid=").append(formerbookid);
        sb.append(", userid=").append(userid);
        sb.append(", formeruserid=").append(formeruserid);
        sb.append(", pulltime=").append(pulltime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}