package com.cjw.yolonote.dao;

import com.cjw.yolonote.pojo.TbFriend;
import com.cjw.yolonote.pojo.TbFriendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbFriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated
     */
    int countByExample(TbFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated
     */
    int deleteByExample(TbFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated
     */
    int insert(TbFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated
     */
    int insertSelective(TbFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated
     */
    List<TbFriend> selectByExample(TbFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated
     */
    TbFriend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbFriend record, @Param("example") TbFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbFriend record, @Param("example") TbFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbFriend record);
}