package com.cjw.yolonote.dao;

import com.cjw.yolonote.pojo.TbFriendRequest;
import com.cjw.yolonote.pojo.TbFriendRequestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbFriendRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_request
     *
     * @mbggenerated
     */
    int countByExample(TbFriendRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_request
     *
     * @mbggenerated
     */
    int deleteByExample(TbFriendRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_request
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_request
     *
     * @mbggenerated
     */
    int insert(TbFriendRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_request
     *
     * @mbggenerated
     */
    int insertSelective(TbFriendRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_request
     *
     * @mbggenerated
     */
    List<TbFriendRequest> selectByExampleWithBLOBs(TbFriendRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_request
     *
     * @mbggenerated
     */
    List<TbFriendRequest> selectByExample(TbFriendRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_request
     *
     * @mbggenerated
     */
    TbFriendRequest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_request
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbFriendRequest record, @Param("example") TbFriendRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_request
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TbFriendRequest record, @Param("example") TbFriendRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_request
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbFriendRequest record, @Param("example") TbFriendRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_request
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbFriendRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_request
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TbFriendRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend_request
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbFriendRequest record);
}