package com.cjw.yolonote.dao;

import com.cjw.yolonote.pojo.TbNoteLabel;
import com.cjw.yolonote.pojo.TbNoteLabelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbNoteLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_label
     *
     * @mbggenerated
     */
    int countByExample(TbNoteLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_label
     *
     * @mbggenerated
     */
    int deleteByExample(TbNoteLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_label
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer labelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_label
     *
     * @mbggenerated
     */
    int insert(TbNoteLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_label
     *
     * @mbggenerated
     */
    int insertSelective(TbNoteLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_label
     *
     * @mbggenerated
     */
    List<TbNoteLabel> selectByExample(TbNoteLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_label
     *
     * @mbggenerated
     */
    TbNoteLabel selectByPrimaryKey(Integer labelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_label
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbNoteLabel record, @Param("example") TbNoteLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_label
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbNoteLabel record, @Param("example") TbNoteLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_label
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbNoteLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_label
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbNoteLabel record);
}