package com.cjw.yolonote.dao;

import com.cjw.yolonote.pojo.TbNoteBookAudit;
import com.cjw.yolonote.pojo.TbNoteBookAuditExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbNoteBookAuditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_audit
     *
     * @mbggenerated
     */
    int countByExample(TbNoteBookAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_audit
     *
     * @mbggenerated
     */
    int deleteByExample(TbNoteBookAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_audit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_audit
     *
     * @mbggenerated
     */
    int insert(TbNoteBookAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_audit
     *
     * @mbggenerated
     */
    int insertSelective(TbNoteBookAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_audit
     *
     * @mbggenerated
     */
    List<TbNoteBookAudit> selectByExampleWithBLOBs(TbNoteBookAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_audit
     *
     * @mbggenerated
     */
    List<TbNoteBookAudit> selectByExample(TbNoteBookAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_audit
     *
     * @mbggenerated
     */
    TbNoteBookAudit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_audit
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbNoteBookAudit record, @Param("example") TbNoteBookAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_audit
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TbNoteBookAudit record, @Param("example") TbNoteBookAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_audit
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbNoteBookAudit record, @Param("example") TbNoteBookAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_audit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbNoteBookAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_audit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TbNoteBookAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_book_audit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbNoteBookAudit record);
}