package com.cjw.yolonote.dao;

import com.cjw.yolonote.pojo.TbNoteFile;
import com.cjw.yolonote.pojo.TbNoteFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbNoteFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_file
     *
     * @mbggenerated
     */
    int countByExample(TbNoteFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_file
     *
     * @mbggenerated
     */
    int deleteByExample(TbNoteFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_file
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer fileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_file
     *
     * @mbggenerated
     */
    int insert(TbNoteFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_file
     *
     * @mbggenerated
     */
    int insertSelective(TbNoteFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_file
     *
     * @mbggenerated
     */
    List<TbNoteFile> selectByExample(TbNoteFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_file
     *
     * @mbggenerated
     */
    TbNoteFile selectByPrimaryKey(Integer fileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_file
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbNoteFile record, @Param("example") TbNoteFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_file
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbNoteFile record, @Param("example") TbNoteFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbNoteFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_note_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbNoteFile record);
}