package com.cjw.yolonote.dao;

import com.cjw.yolonote.pojo.TbUserPassword;
import com.cjw.yolonote.pojo.TbUserPasswordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbUserPasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_password
     *
     * @mbggenerated
     */
    int countByExample(TbUserPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_password
     *
     * @mbggenerated
     */
    int deleteByExample(TbUserPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_password
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_password
     *
     * @mbggenerated
     */
    int insert(TbUserPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_password
     *
     * @mbggenerated
     */
    int insertSelective(TbUserPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_password
     *
     * @mbggenerated
     */
    List<TbUserPassword> selectByExample(TbUserPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_password
     *
     * @mbggenerated
     */
    TbUserPassword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_password
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbUserPassword record, @Param("example") TbUserPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_password
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbUserPassword record, @Param("example") TbUserPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_password
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbUserPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_password
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbUserPassword record);
}